local skills = {}

local Skill = {
  acrobatics = "acrobatics",
  alchemy = "alchemy",
  alteration = "alteration",
  armorer = "armorer",
  athletics = "athletics",
  axe = "axe",
  bluntWeapon = "bluntWeapon",
  block = "block",
  conjuration = "conjuration",
  destruction = "destruction",
  enchant = "enchant",
  handToHand = "handToHand",
  heavyArmor = "heavyArmor",
  illusion = "illusion",
  lightArmor = "lightArmor",
  longBlade = "longBlade",
  marksman = "marksman",
  mediumArmor = "mediumArmor",
  mercantile = "mercantile",
  mysticism = "mysticism",
  restoration = "restoration",
  security = "security",
  shortBlade = "shortBlade",
  sneak = "sneak",
  spear = "spear",
  speechcraft = "speechcraft",
  unarmored = "unarmored",
}

skills.Skill = Skill

skills.skills = {
  [Skill.acrobatics] = {
    name = "Acrobatics",
    shortName = "ACR",
    id = Skill.acrobatics,
  },
  [Skill.alchemy] = {
    name = "Alchemy",
    shortName = "ALC",
    id = Skill.alchemy,
  },
  [Skill.alteration] = {
    name = "Alteration",
    shortName = "ALT",
    id = Skill.alteration,
  },
  [Skill.armorer] = {
    name = "Armorer",
    shortName = "ARM",
    id = Skill.armorer,
  },
  [Skill.athletics] = {
    name = "Athletics",
    shortName = "ATH",
    id = Skill.athletics,
  },
  [Skill.axe] = {
    name = "Axe",
    shortName = "AXE",
    id = Skill.axe,
  },
  [Skill.bluntWeapon] = {
    name = "Blunt Weapon",
    shortName = "BLT",
    id = Skill.bluntWeapon,
  },
  [Skill.block] = {
    name = "Block",
    shortName = "BLK",
    id = Skill.block,
  },
  [Skill.conjuration] = {
    name = "Conjuration",
    shortName = "CNJ",
    id = Skill.conjuration,
  },
  [Skill.destruction] = {
    name = "Destruction",
    shortName = "DES",
    id = Skill.destruction,
  },
  [Skill.enchant] = {
    name = "Enchant",
    shortName = "ENC",
    id = Skill.enchant,
  },
  [Skill.handToHand] = {
    name = "Hand To Hand",
    shortName = "HTH",
    id = Skill.handToHand,
  },
  [Skill.heavyArmor] = {
    name = "Heavy Armor",
    shortName = "HVY",
    id = Skill.heavyArmor,
  },
  [Skill.illusion] = {
    name = "Illusion",
    shortName = "ILU",
    id = Skill.illusion,
  },
  [Skill.lightArmor] = {
    name = "Light Armor",
    shortName = "LGT",
    id = Skill.lightArmor,
  },
  [Skill.longBlade] = {
    name = "Long Blade",
    shortName = "LBL",
    id = Skill.longBlade,
  },
  [Skill.marksman] = {
    name = "Marksman",
    shortName = "MAR",
    id = Skill.marksman,
  },
  [Skill.mediumArmor] = {
    name = "Medium Armor",
    shortName = "MED",
    id = Skill.mediumArmor,
  },
  [Skill.mercantile] = {
    name = "Mercantile",
    shortName = "MRC",
    id = Skill.mercantile,
  },
  [Skill.mysticism] = {
    name = "Mysticism",
    shortName = "MYS",
    id = Skill.mysticism,
  },
  [Skill.restoration] = {
    name = "Restoration",
    shortName  = "RST",
    id = Skill.restoration,
  },
  [Skill.security] = {
    name = "Security",
    shortName = "SEC",
    id = Skill.security,
  },
  [Skill.shortBlade] = {
    name = "Short Blade",
    shortName = "SBL",
    id = Skill.shortBlade,
  },
  [Skill.sneak] = {
    name = "Sneak",
    shortName = "SNK",
    id = Skill.sneak,
  },
  [Skill.spear] = {
    name = "Spear",
    shortName = "SPR",
    id = Skill.spear,
  },
  [Skill.speechcraft] = {
    name = "Speechcraft",
    shortName = "SPC",
    id = Skill.speechcraft,
  },
  [Skill.unarmored] = {
    name = "Unarmored",
    shortName = "UNM",
    id = Skill.unarmored,
  },
}

skills.skillBookMap = {
  bookskill_acrobatics1 = Skill.acrobatics,
  BookSkill_Acrobatics2 = Skill.acrobatics,
  BookSkill_Acrobatics3 = Skill.acrobatics,
  BookSkill_Acrobatics4 = Skill.acrobatics,
  BookSkill_Acrobatics5 = Skill.acrobatics,
  BookSkill_Alchemy1 = Skill.alchemy,
  BookSkill_Alchemy2 = Skill.alchemy,
  BookSkill_Alchemy3 = Skill.alchemy,
  BookSkill_Alchemy4 = Skill.alchemy,
  BookSkill_Alchemy5 = Skill.alchemy,
  sc_GrandfatherFrost = Skill.alchemy,
  sc_unclesweetshare = Skill.alchemy,
  BookSkill_Alteration1 = Skill.alteration,
  BookSkill_Alteration2 = Skill.alteration,
  BookSkill_Alteration3 = Skill.alteration,
  BookSkill_Alteration4 = Skill.alteration,
  BookSkill_Alteration5 = Skill.alteration,
  BookSkill_Armorer1 = Skill.armorer,
  BookSkill_Armorer2 = Skill.armorer,
  BookSkill_Armorer3 = Skill.armorer,
  BookSkill_Armorer4 = Skill.armorer,
  BookSkill_Armorer5 = Skill.armorer,
  BookSkill_Athletics1 = Skill.athletics,
  BookSkill_Athletics2 = Skill.athletics,
  BookSkill_Athletics3 = Skill.athletics,
  BookSkill_Athletics4 = Skill.athletics,
  BookSkill_Athletics5 = Skill.athletics,
  BookSkill_Axe1 = Skill.axe,
  bookskill_axe2 = Skill.axe,
  BookSkill_Axe3 = Skill.axe,
  BookSkill_Axe4 = Skill.axe,
  BookSkill_Axe5 = Skill.axe,
  BookSkill_Axe5_open = Skill.axe,
  BookSkill_Block1 = Skill.block,
  bookskill_block2 = Skill.block,
  BookSkill_Block3 = Skill.block,
  BookSkill_Block4 = Skill.block,
  BookSkill_Block5 = Skill.block,
  ["bookskill_blunt weapon1"] = Skill.bluntWeapon,
  ["BookSkill_Blunt Weapon2"] = Skill.bluntWeapon,
  ["bookskill_blunt weapon3"] = Skill.bluntWeapon,
  ["BookSkill_Blunt Weapon4"] = Skill.bluntWeapon,
  ["BookSkill_Blunt Weapon5"] = Skill.bluntWeapon,
  BookSkill_Conjuration1 = Skill.conjuration,
  BookSkill_Conjuration2 = Skill.conjuration,
  BookSkill_Conjuration3 = Skill.conjuration,
  BookSkill_Conjuration4 = Skill.conjuration,
  bookskill_conjuration5 = Skill.conjuration,
  bookskill_destruction1 = Skill.destruction,
  bookskill_destruction2 = Skill.destruction,
  bookskill_destruction3 = Skill.destruction,
  bookskill_destruction4 = Skill.destruction,
  BookSkill_Destruction5 = Skill.destruction,
  BookSkill_Destruction5_open = Skill.destruction,
  BookSkill_Enchant1 = Skill.enchant,
  BookSkill_Enchant2 = Skill.enchant,
  bookskill_enchant3 = Skill.enchant,
  bookskill_enchant4 = Skill.enchant,
  bookskill_enchant5 = Skill.enchant,
  ["bookskill_hand to hand1"] = Skill.handToHand,
  ["bookskill_hand to hand2"] = Skill.handToHand,
  ["bookskill_hand to hand3"] = Skill.handToHand,
  ["bookskill_hand to hand4"] = Skill.handToHand,
  ["bookskill_hand to hand5"] = Skill.handToHand,
  ["bookskill_heavy armor1"] = Skill.heavyArmor,
  ["BookSkill_Heavy Armor2"] = Skill.heavyArmor,
  ["BookSkill_Heavy Armor3"] = Skill.heavyArmor,
  ["bookskill_heavy armor4"] = Skill.heavyArmor,
  ["bookskill_heavy armor5"] = Skill.heavyArmor,
  bookskill_illusion1 = Skill.illusion,
  bookskill_illusion2 = Skill.illusion,
  bookskill_illusion3 = Skill.illusion,
  bookskill_illusion4 = Skill.illusion,
  bookskill_illusion5 = Skill.illusion,
  ["BookSkill_Light Armor1"] = Skill.lightArmor,
  ["BookSkill_Light Armor2"] = Skill.lightArmor,
  ["bookskill_light_armor3"] = Skill.lightArmor,
  ["bookskill_light armor4"] = Skill.lightArmor,
  ["bookskill_light armor5"] = Skill.lightArmor,
  ["BookSkill_Long Blade1"] = Skill.longBlade,
  ["BookSkill_Long Blade2"] = Skill.longBlade,
  ["bookskill_long blade3"] = Skill.longBlade,
  ["bookskill_long blade4"] = Skill.longBlade,
  ["bookskill_long blade5"] = Skill.longBlade,
  bookskill_marksman1 = Skill.marksman,
  BookSkill_Marksman2 = Skill.marksman,
  bookskill_marksman3 = Skill.marksman,
  bookskill_marksman4 = Skill.marksman,
  bookskill_marksman5 = Skill.marksman,
  ["bookskill_medium armor1"] = Skill.mediumArmor,
  ["BookSkill_Medium Armor2"] = Skill.mediumArmor,
  ["BookSkill_Medium Armor3"] = Skill.mediumArmor,
  ["bookskill_medium armor4"] = Skill.mediumArmor,
  ["bookskill_medium armor5"] = Skill.mediumArmor,
  bookskill_mercantile1 = Skill.mercantile,
  bookskill_mercantile2 = Skill.mercantile,
  BookSkill_Mercantile3 = Skill.mercantile,
  bookskill_mercantile4 = Skill.mercantile,
  bookskill_mercantile5 = Skill.mercantile,
  bookskill_mysticism1 = Skill.mysticism,
  BookSkill_Mysticism2 = Skill.mysticism,
  BookSkill_Mysticism3 = Skill.mysticism,
  BookSkill_Mysticism4 = Skill.mysticism,
  BookSkill_Mysticism5 = Skill.mysticism,
  bookskill_restoration1 = Skill.restoration,
  bookskill_restoration2 = Skill.restoration,
  bookskill_restoration3 = Skill.restoration,
  BookSkill_Restoration4 = Skill.restoration,
  BookSkill_Restoration5 = Skill.restoration,
  bookskill_security1 = Skill.security,
  bookskill_security2 = Skill.security,
  BookSkill_Security3 = Skill.security,
  bookskill_security4 = Skill.security,
  bookskill_security5 = Skill.security,
  sc_fjellnote = Skill.security,
  sc_sjobalnote = Skill.security,
  ["bookskill_short blade1"] = Skill.shortBlade,
  ["BookSkill_Short Blade2"] = Skill.shortBlade,
  ["BookSkill_Short Blade3"] = Skill.shortBlade,
  ["BookSkill_Short Blade4"] = Skill.shortBlade,
  ["BookSkill_Short Blade5"] = Skill.shortBlade,
  bookskill_sneak1 = Skill.sneak,
  BookSkill_Sneak2 = Skill.sneak,
  BookSkill_Sneak3 = Skill.sneak,
  bookskill_sneak4 = Skill.sneak,
  bookskill_sneak5 = Skill.sneak,
  bookskill_spear1 = Skill.spear,
  BookSkill_Spear2 = Skill.spear,
  bookskill_spear3 = Skill.spear,
  bookskill_spear4 = Skill.spear,
  bookskill_spear5 = Skill.spear,
  BookSkill_Speechcraft1 = Skill.speechcraft,
  bookskill_speechcraft2 = Skill.speechcraft,
  BookSkill_Speechcraft3 = Skill.speechcraft,
  bookskill_speechcraft4 = Skill.speechcraft,
  bookskill_speechcraft5 = Skill.speechcraft,
  bookskill_unarmored1 = Skill.unarmored,
  bookskill_unarmored2 = Skill.unarmored,
  bookskill_unarmored3 = Skill.unarmored,
  bookskill_unarmored4 = Skill.unarmored,
  bookskill_unarmored5 = Skill.unarmored,
}

function skills.getBookSkill(bookId)
  local skill
  local skillId = skills.skillBookMap[bookId]
  if skillId then
    skill = skills.skills[skillId]
  end
  return skill
end

return skills